application: mylibraweight
version: 2
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

# favicon.ico
- url: /favicon.ico
  mime_type: image/x-icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app
  login: optional